name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: ['386']
        frp_version: ['0.27.1']
    steps:
    - uses: actions/checkout@v1
    - name: Fetch frpc release bin file.
      env:
        FRP_RELEASE_FILE_NAME: frp_${{ matrix.frp_version }}_freebsd_${{ matrix.arch }}
        FRP_RELEASE_FILE_URL: https://github.com/fatedier/frp/releases/download/v${{ matrix.frp_version }}/frp_${{ matrix.frp_version }}_freebsd_${{ matrix.arch }}.tar.gz
      run: |
        curl -L $FRP_RELEASE_FILE_URL | tar -xf -C resource/bin $FRP_RELEASE_FILENAME/frpc --strip-components 1
        ls -ll resource/bin
