name: Auto Build On Release

on: release

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: ['386']
        frp_version: ['0.27.1']
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Fetch frpc bin file
        env:
          FRP_RELEASE_FILE_URL: https://github.com/fatedier/frp/releases/download/v${{ matrix.frp_version }}/frp_${{ matrix.frp_version }}_freebsd_${{ matrix.arch }}.tar.gz
          FRPC_BIN_FILE_PATH: frp_${{ matrix.frp_version }}_freebsd_${{ matrix.arch }}/frpc
        run: curl -sL ${FRP_RELEASE_FILE_URL} | tar -xz -C resource/bin ${FRPC_BIN_FILE_PATH} --strip-components 1
      - name: Build Panabit App package
        env:
          APP_ID: app_tcz_fprc
          APP_NAME: frpc
          APP_CNAME: frpc
          APP_WIDTH: 1000
          APP_HEIGHT: 700
          APP_DESC: "frp is a fast reverse proxy to help you expose a local server behind a NAT or firewall to the internet."
          APP_VERSION: $(date +%Y%m%d)_${{ matrix.frp_version }}
          APP_FRPC_VERSION: ${{ matrix.frp_version }}
          APP_BUILD_DATE: $(date +"%Y-%m-%d %H:%M:%S")
        run: |
          mkdir -p dist/tmp
          cp -r scripts/* dist/tmp
          tar -czf dist/tmp/resource.tar.gz --exclude=.gitkeep -C resource .
          envsubst < app.inf.template > dist/tmp/app.inf
          tar -czf dist/PanabitApp-${APP_NAME}_${APP_VERSION}.apx  -C dist/tmp .
      - name: Upload asset to release
        uses: actions-github/upload-to-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          type: 'application/octet-stream'
          file: 'dist/PanabitApp-${APP_NAME}_${APP_VERSION}.apx'
