#!/bin/sh

RAM_DISK="/usr/ramdisk"
APP_NAME=frpc
APP_RUN_ROOT="${RAM_DISK}/app/${APP_NAME}"

if [ -f ../../app_env ]; then
    . ../../app_env
else
    . "${APP_RUN_ROOT}/app_env"
fi

printf "Content-type: text/html; charset=UTF-8\r\n"
printf "Cache-Control: no-cache\r\n"
printf "\r\n"
cat "${APP_WEB_HTML_ROOT}/index.html"
